version : '3'
services :
  client:
    build: client/.
    env_file:
      - client/.env
    container_name: 'myJobTracker-Client'
    command: 'yarn start'
    stdin_open: true
    ports:
      - '5000:5000'
      - '3000:3000'
    volumes:
      - './client/:/root/myJobTracker/client:cached'
  server:
    build: server/.
    env_file:
      - server/.env
    container_name: 'myJobTracker-Server'
    command: 'yarn start'
    ports:
      - '8808:8808'
    volumes:
      - './server/:/root/myJobTracker/server:cached'
    depends_on:
      - mongoDB
    links:
      - mongoDB
  mongoDB:
    image: 'mongo'
    container_name: 'mongo_container'
    env_file:
      - .env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'


